name: Check Previous Workflows Status

on:
  workflow_run:
    workflows:
      - Run something that always passes
      - Run something that always passes 2
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Workflows Status
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = "${{ github.event.workflow_run.head_commit.id }}";
            const workflow_ids = ["First Workflow Name", "Second Workflow Name"]; // Use actual workflow file names or IDs
            let allSucceeded = true;

            for (const workflow_id of workflow_ids) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id,
                branch: "main", // Adjust this as necessary
              });
              const recentRun = runs.data.workflow_runs.find(run => run.head_sha === sha);
              if (!recentRun || recentRun.conclusion !== 'success') {
                allSucceeded = false;
                break;
              }
            }

            return allSucceeded;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Outcome
        if: steps.check.outputs.result == 'true'
        run: echo "All specified workflows succeeded for this commit."
