name: Check Previous Workflows Status

on:
  workflow_run:
    workflows:
      - Run something that always passes
      - Run something that always passes 2
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Workflows Status
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./path/to/script.js');
            return await script({github, context, core});
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Outcome
        if: steps.check.outputs.result == 'true'
        run: echo "All specified workflows succeeded for this commit."
